# 
# Functions that generate C code

# Generate c code given a template
# Tags take the form [[template::<tag>]]
gen_c_code <- function(parameters,         # System list
                       template,           # Template file
                       output=NULL,        # 
                       overwrite=FALSE,    #   
                       tags_list=NULL,     # tags list
                       tags_funs=NULL) {   # tags function
  
  if (is.null(tags_list)) {
    tags_list <- list('declarations', 'defines')
  }
  if (is.null(tags_funs)) {
    tags_funs <- list(gen_declarations, gen_defines)
  }
  if (is.null(output)) { 
    output <- gen_output(template)
  }
  
  # Read template
  txt <- readChar(template, file.info(template)$size)
  
  # Replace all tags
  for (n in seq.int(length(tags_list))) {
    message('Replacing ', mktag(tags_list[[n]]))
    txt <- replaceonetag(txt, 
                         tags_list[[n]], 
                         tags_funs[[n]](parameters))
  }
  
  if (file.exists(output) && !overwrite) {
    stop(paste0("Output file exists (",
                output,"). Override with overwrite=TRUE"))
  }
  
  writeChar(txt,output, eos=NULL)
  message('Wrote .c file to ', output)
  
  invisible(txt)
}

# Removes generated c files
clean_c_code <- function(template_dir) { 
  for (file in dir(template_dir, full.names=TRUE)) { 
    file_output <- gen_output(file)
    message('Removing ', file_output)
    if (file.exists(file_output)) file.remove(file_output)
  }
}

# Tag replacement
# ------------------------------------------

# Replace a tag name with correct elements
replaceonetag <- function(text, tagstring, what) { 
  sub(mktag(tagstring), mkrep(what), text, fixed=TRUE)
}

# Provide R timestamp
mkrep <- function(str) { 
  paste0('// Generated by R (', date(),')\n',str)
}

# Make pattern to replace from a tag string
mktag <- function(str) { 
  paste0("[[template::",str,"]]")
} 

# Generators
# ------------------------------------------

gen_defines <- function(plist, collapser="\n") { 
  
  nspecies <- lapply(plist, function(x) vecmat_switch(x, length(x), ncol(x)))
  nparams  <- Reduce(sum, lapply(plist, length))
  
  txt <- paste0("#define Nsp ", nspecies[[1]], "\n",
                "#define Np ",  nparams,       "\n")
  
  return(txt)
}

# Generate all values declaration ( double XX[Nsp][Nsp] ) given a list of
# parameters.
gen_declarations <- function(plist) { 
  
  declarations <- mapply(gen_onedeclaration, 
                         names(plist),
                         plist)
  
  paste(declarations, collapse="\n")
}
gen_onedeclaration <- function(parm.name, parm.value) {
  paste0('double ', parm.name, 
         gen_size_qualifier(parm.value), ";")
}

# Utils 
# ------------------------------------------
gen_size_qualifier <- function(elem) { 
    vecmat_switch(elem, 
                  paste0("[", length(elem),"]"),
                  paste0("[", nrow(elem),  "]", "[", ncol(elem),"]"))
}

# Checks if an element is a matrix or a vector or else
vecmat_switch <- function(thing, isvec, ismat, elsefun=stop) { 
  # Get size of element
  if (is.vector(thing)) { 
    return(isvec)
  } else if (is.matrix(thing)) { 
    return(ismat)
  } else { 
    stop('Not a matrix or a vector, check input')
  }
}

# Returns the output name of a template
gen_output <- function(str) { 
  paste0(dirname(str), '/../', sub(".template","", basename(str)))
}
