// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// select_range
NumericMatrix select_range(NumericMatrix inmat, double tmin, double tmax);
RcppExport SEXP netmodr_select_range(SEXP inmatSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type inmat(inmatSEXP );
        Rcpp::traits::input_parameter< double >::type tmin(tminSEXP );
        Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP );
        NumericMatrix __result = select_range(inmat, tmin, tmax);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// zero_below
NumericMatrix zero_below(NumericMatrix old, double eps);
RcppExport SEXP netmodr_zero_below(SEXP oldSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type old(oldSEXP );
        Rcpp::traits::input_parameter< double >::type eps(epsSEXP );
        NumericMatrix __result = zero_below(old, eps);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
