// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// bmgen_mrates
NumericVector bmgen_mrates(NumericVector bodyms, double mr0, double mr0exp);
RcppExport SEXP netmodr_bmgen_mrates(SEXP bodymsSEXP, SEXP mr0SEXP, SEXP mr0expSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type bodyms(bodymsSEXP );
        Rcpp::traits::input_parameter< double >::type mr0(mr0SEXP );
        Rcpp::traits::input_parameter< double >::type mr0exp(mr0expSEXP );
        NumericVector __result = bmgen_mrates(bodyms, mr0, mr0exp);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// bmgen_arates
NumericMatrix bmgen_arates(NumericVector bodyms, NumericVector mrates, double a0, double eps);
RcppExport SEXP netmodr_bmgen_arates(SEXP bodymsSEXP, SEXP mratesSEXP, SEXP a0SEXP, SEXP epsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type bodyms(bodymsSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type mrates(mratesSEXP );
        Rcpp::traits::input_parameter< double >::type a0(a0SEXP );
        Rcpp::traits::input_parameter< double >::type eps(epsSEXP );
        NumericMatrix __result = bmgen_arates(bodyms, mrates, a0, eps);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// mortality
NumericVector mortality(NumericVector X, NumericVector m);
RcppExport SEXP netmodr_mortality(SEXP XSEXP, SEXP mSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type m(mSEXP );
        NumericVector __result = mortality(X, m);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// fresp_type2
NumericMatrix fresp_type2(NumericVector X, NumericMatrix atk, NumericVector h);
RcppExport SEXP netmodr_fresp_type2(SEXP XSEXP, SEXP atkSEXP, SEXP hSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type atk(atkSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type h(hSEXP );
        NumericMatrix __result = fresp_type2(X, atk, h);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// rockyshore
List rockyshore(NumericVector times, NumericVector X, List p);
RcppExport SEXP netmodr_rockyshore(SEXP timesSEXP, SEXP XSEXP, SEXP pSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type times(timesSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP );
        Rcpp::traits::input_parameter< List >::type p(pSEXP );
        List __result = rockyshore(times, X, p);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
