# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

frtype2 <- function(X, A, B0) {
    .Call('netmodr_frtype2', PACKAGE = 'netmodr', X, A, B0)
}

loggrowth <- function(X, R, K) {
    .Call('netmodr_loggrowth', PACKAGE = 'netmodr', X, R, K)
}

