# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

zero_below_cpp <- function(old, eps) {
    .Call('netmodr_zero_below_cpp', PACKAGE = 'netmodr', old, eps)
}

